const $=s=>document.querySelector(s);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const variant=['a','b','c'].includes(new URLSearchParams(location.search).get('v'))?new URLSearchParams(location.search).get('v'):'a';
document.body.className='variant-'+variant;
document.querySelector(`[data-variant="${variant}"]`).classList.add('active');
const names={a:'效率列表',b:'待办优先',c:'连续阅读'};
const titles={jobs:'岗位机会',tasks:'自动任务',profile:'我的简历',settings:'偏好与设置'};
const state={page:'jobs',view:variant==='b'?'attention':'recommended',query:'',salary:'',activity:'',selected:null,detailTab:'match',settingsTab:'preferences',dirty:false,style:'自然真诚',researchOn:true,collectionOn:true,loginRequired:true,analysisOn:true,profileVersion:1};
let settingValues=new Map(),savedSettingValues=new Map(),savedStyle=state.style;
const jobs=[
 {id:1,title:'B端产品经理',company:'沐川软件',salary:'22–32K',min:22,max:32,place:'深圳 · 南山',active:'今日活跃',fit:'优先沟通',reason:'企业服务流程与跨系统交付经验直接匹配',gap:'需要确认行业知识的上手要求',status:'new',research:'已核对公开资料',industry:'企业协同软件',scale:'100–499人（招聘方自述）'},
 {id:2,title:'SaaS高级产品经理',company:'远帆云科技',salary:'25–35K',min:25,max:35,place:'深圳 · 福田',active:'本周活跃',fit:'优先沟通',reason:'0—1商业化与多角色产品设计经验相关',gap:'续费和增长指标的职责范围待确认',status:'new',research:'资料待核实',industry:'商家经营SaaS',scale:'团队规模尚未核实'},
 {id:3,title:'AI应用产品经理',company:'观澜智能',salary:'25–40K',min:25,max:40,place:'深圳 · 南山',active:'今日活跃',fit:'可以尝试',reason:'智能审核经验可迁移，Agent落地要求待核实',gap:'没有完整主导LLM Agent商业交付的实证',status:'replied',research:'已核对公开资料',industry:'企业AI应用',scale:'50–99人（招聘方自述）',message:'您好，方便介绍一下您做过的AI产品，以及本人负责的部分吗？'},
 {id:4,title:'平台产品经理',company:'合序数科',salary:'20–30K',min:20,max:30,place:'深圳 · 宝安',active:'本周活跃',fit:'优先沟通',reason:'多方权责梳理、交易与履约流程高度相关',gap:'具体平台的盈利模式仍需沟通',status:'waiting',research:'背调中',industry:'产业服务平台',scale:'未核实'},
 {id:5,title:'内容安全产品经理',company:'青禾网络',salary:'23–33K',min:23,max:33,place:'深圳 · 南山',active:'今日活跃',fit:'优先沟通',reason:'机审、人审协同及客户交付有直接经验',gap:'算法团队分工与效果指标需确认',status:'managed',research:'已核对公开资料',industry:'内容安全服务',scale:'未核实'},
 {id:6,title:'物联网产品经理',company:'森序智控',salary:'18–28K',min:18,max:28,place:'深圳 · 龙岗',active:'未知 / 未展示',fit:'可以尝试',reason:'设备联动与节能产品经验可迁移',gap:'硬件供应链与量产职责尚无明确实证',status:'saved',research:'资料待核实',industry:'楼宇智能控制',scale:'未核实'},
 {id:7,title:'软件产品经理',company:'星渡企业服务',salary:'20–28K',min:20,max:28,place:'深圳 · 福田',active:'本周活跃',fit:'可以尝试',reason:'需求分析与产品交付能力匹配',gap:'消息发送结果不确定，需要核对后再行动',status:'check',research:'资料待核实',industry:'企业数字化',scale:'未核实'},
 {id:8,title:'电商中台产品经理',company:'栖木商贸',salary:'20–30K',min:20,max:30,place:'深圳 · 龙华',active:'本周活跃',fit:'可以尝试',reason:'电商业务经验相关，内部系统建设经验有缺口',gap:'没有完整0—1主导电商ERP/WMS系统经历',status:'new',research:'背调中',industry:'跨境电商',scale:'未核实'}
];
const statusName={new:'尚未沟通',saved:'已收藏',replied:'HR已回复',waiting:'待HR回复',managed:'AI沟通中',check:'发送待核对',followup:'由我跟进',ignored:'暂不考虑'};
const counts=()=>({recommended:jobs.filter(j=>['new','saved'].includes(j.status)).length,attention:jobs.filter(j=>['replied','check'].includes(j.status)).length,communicating:jobs.filter(j=>['waiting','managed','followup'].includes(j.status)).length,all:jobs.length});
function rows(){return jobs.filter(j=>{
 const inView=state.view==='all'||state.view==='recommended'&&['new','saved'].includes(j.status)||state.view==='attention'&&['replied','check'].includes(j.status)||state.view==='communicating'&&['waiting','managed','followup'].includes(j.status);
 const activityMatch=!state.activity||(state.activity==='unknown'?j.active.startsWith('未知'):!j.active.startsWith('未知'));
 return inView&&activityMatch&&(!state.query||[j.title,j.company,j.place].join(' ').toLowerCase().includes(state.query.toLowerCase()))&&(!state.salary||j.max>=Number(state.salary));
});}
function notify(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').hidden=true,3300);}
function tag(j){return `<span class="tag ${j.fit==='可以尝试'?'amber':''}">${j.fit}</span>`;}
function nav(){const c=counts();$('#nav').innerHTML=Object.entries(titles).map(([key,title])=>`<button data-page="${key}" class="${state.page===key?'active':''}" aria-current="${state.page===key?'page':'false'}">${title}${key==='jobs'&&c.attention?`<small>${c.attention}</small>`:''}</button>`).join('');}
function draw(){nav();$('#eyebrow').textContent=`循序 / ${names[variant]}`;$('#page-title').textContent=state.page==='jobs'&&variant==='b'?'先处理值得回应的机会':titles[state.page];$('#page-actions').innerHTML=state.page==='jobs'?'<span class="muted">模拟运行 · 刚刚更新</span>': '<span class="tag neutral">交互演示</span>';if(state.page==='jobs')drawJobs();if(state.page==='tasks')drawTasks();if(state.page==='profile')drawProfile();if(state.page==='settings')drawSettings();}
function drawJobs(){const c=counts();$('#page').innerHTML=`${variant==='b'?`<div class="attention-band"><div><strong>${c.attention}</strong>件事等你处理<p>HR回复与发送核对优先，后台任务不抢占你的注意力。</p></div><button data-view="attention">处理待办 →</button></div>`:''}<div class="view-tabs" role="tablist" aria-label="岗位视图">${[['recommended','值得沟通'],['attention','待我处理'],['communicating','沟通中'],['all','全部']].map(([k,label])=>`<button role="tab" aria-selected="${state.view===k}" data-view="${k}" class="${state.view===k?'active':''}">${label}<b>${c[k]}</b></button>`).join('')}</div><div class="toolbar"><label class="search-wrap"><input id="search" aria-label="搜索岗位或公司" placeholder="搜索岗位、公司" value="${escape(state.query)}"></label><button data-action="filter">筛选${state.salary||state.activity?' · 已选':''}</button><button data-page="tasks" class="quiet">${variant==='b'?'后台任务':'任务'}</button><span class="results-note" id="results-count"></span></div><div id="chips" class="filter-chips"></div><div id="job-region"></div>`;drawJobRegion();}
function drawJobRegion({keepSelection=false}={}){const shown=rows();$('#results-count').textContent=`${shown.length} 个岗位 · 全部为虚构演示`;
 $('#chips').innerHTML=[state.salary?`<button data-clear="salary">薪资 ≥${state.salary}K有交集 ×</button>`:'',state.activity?`<button data-clear="activity">${state.activity==='week'?'本周及更近期':'未知活跃'} ×</button>`:''].join('');
 const empty='<div class="empty"><h3>没有符合条件的岗位</h3><p>试试清除筛选条件，或切换到全部岗位。</p><button data-action="reset-filter">清除筛选，查看全部</button></div>';
 if(variant==='c'){
  if(!keepSelection&&!shown.some(j=>j.id===state.selected))state.selected=shown[0]?.id||null;
  $('#job-region').innerHTML=`<div class="reading-layout"><div class="list">${shown.length?shown.map(j=>`<article class="job-row ${j.id===state.selected?'selected':''}"><span class="salary">${j.salary}</span><button class="job-title" data-open="${j.id}">${j.title}</button><div class="job-company">${j.company} · ${j.place}</div><div class="fit-line">${tag(j)}<div>${j.reason}</div></div><div class="row-state"><span>${statusName[j.status]}</span><button class="row-open" data-open="${j.id}">查看 →</button></div></article>`).join(''):empty}</div><section class="reading-pane" aria-label="常驻岗位详情">${state.selected?detail(jobs.find(j=>j.id===state.selected),true):'<div class="read-placeholder">选择一个岗位，边看边比较</div>'}</section></div>`;
 }else if(variant==='b'){
  $('#job-region').innerHTML=`<div class="section-label"><span>${state.view==='attention'?'需要你做决定':'按下一步行动排列'}</span><span>${shown.length} 个机会</span></div><div class="list task-inbox">${shown.length?shown.map(j=>`<article class="job-row"><span class="avatar">${j.company.slice(0,1)}</span><div><button data-open="${j.id}" class="job-title">${j.title}</button><div class="job-company">${j.company} · ${j.salary}</div></div><div class="inbox-reason">${j.status==='replied'?j.message:j.status==='check'?'无法确认上次消息是否送达，先核对，不重发。':j.reason}<small>${statusName[j.status]} · ${j.active}</small></div><button class="row-open" data-open="${j.id}">${j.status==='replied'?'看回复':j.status==='check'?'去核对':'看机会'} →</button></article>`).join(''):empty}</div>`;
 }else $('#job-region').innerHTML=`<div class="list"><div class="list-head"><span>岗位 / 公司</span><span>薪资 / 地区</span><span>为什么推荐</span><span>当前进度</span><span>操作</span></div>${shown.length?shown.map(j=>`<article class="job-row"><div><button class="job-title" data-open="${j.id}">${j.title}</button><div class="job-company">${j.company} · ${j.active}</div></div><div class="salary">${j.salary}<span class="location">${j.place}</span></div><div class="fit-line">${tag(j)}<div>${j.reason}</div></div><div class="row-state">${statusName[j.status]}<small>${j.research}</small></div><button class="row-open" data-open="${j.id}">查看 →</button></article>`).join(''):empty}</div>`;
}
function detail(j,inline=false){
 const chat=['replied','managed','waiting','followup','check'].includes(j.status);
 let body='';
 if(state.detailTab==='match')body=`<div class="verdict"><strong>${j.fit}，但有事项需要确认</strong><p>${j.reason}。</p></div><h3>能用经历说清楚的匹配点</h3><ul><li>能梳理企业客户的业务流程、角色权责及系统边界。</li><li>有产品从需求验证到交付上线的实践。</li></ul><h3>面试前需要补齐的信息</h3><div class="warning">${j.gap}。以上为示例判断，不是真实人岗分析。</div><h3>建议先问HR</h3><p>这个岗位目前最希望解决的业务问题是什么？产品经理与运营、技术团队分别负责哪些部分？</p><div class="evidence-line"><b>依据来源</b><small>此处演示“岗位要求 ↔ 简历原文”的证据定位；没有使用你的真实简历。</small></div>`;
 if(state.detailTab==='research')body=`<span class="tag ${j.research==='资料待核实'?'amber':'neutral'}">${j.research}</span><h3>公司是做什么的</h3><p>${j.company}：${j.industry}。这一栏先提供业务概况，再展开完整证据。</p><h3>最值得确认的两件事</h3><ul><li>${j.scale}，不等同于已核实的员工数量。</li><li>实际签约主体、团队业务收入及岗位职责边界仍需确认。</li></ul><div class="warning">全部为虚构演示。资料不足不等于没有风险，也不显示“安全公司”结论。</div><details><summary>展开报告与来源示例</summary><p>主营业务、规模线索、新闻奖项、风险线索分别列出原文引用。正式版本只接受真实读取并验证的来源。</p><p>此原型不连接搜索服务、不编造来源链接。</p></details>`;
 if(state.detailTab==='jd')body=`<h3>${j.title}</h3><p>${j.salary} · ${j.place} · 3–5年 · 本科</p><h3>工作内容（虚构示例）</h3><ul><li>理解业务目标，梳理多角色场景及业务流程。</li><li>制定产品方案，推进研发、上线与效果复盘。</li><li>协同业务及交付团队，持续改进客户体验。</li></ul><h3>招聘信息</h3><p>招聘者：${j.active}<br>首次发现：今天（不是发布日期）</p><div class="warning">这是用于比较界面的示例JD，不能用于真实投递。</div>`;
 if(state.detailTab==='chat')body=`<div class="tag ${j.status==='check'?'amber':'neutral'}">${statusName[j.status]}</div>${j.status==='check'?'<div class="warning">上次发送未取得明确确认。先核对，程序不会直接重发。</div>':''}<div class="message out"><small>我 · 示例招呼</small>您好，我关注这个岗位，有企业服务产品与交付相关经验，希望进一步了解业务目标。</div>${j.message?`<div class="message"><small>HR · 示例回复</small>${escape(j.message)}</div>`:'<p class="muted">暂无新的示例回复。</p>'}${j.reply?`<div class="message out"><small>我 · 模拟回复</small>${escape(j.reply)}</div>`:''}${['replied','followup'].includes(j.status)?'<label>我的回复<textarea id="reply" placeholder="输入示例回复，不会发送给任何人"></textarea></label>':''}${['waiting','managed'].includes(j.status)?'<button data-action="mock-reply" class="quiet">模拟收到HR回复</button>':''}<h3>备注</h3><textarea id="note" aria-label="岗位备注" placeholder="下一步想确认什么？">${escape(j.note||'')}</textarea><button data-action="save-note" class="quiet">保存演示备注</button>`;
 let actions=j.status==='check'?'<button class="primary" data-action="reconcile">核对发送结果（模拟）</button>':j.status==='managed'?'<button class="primary" data-action="takeover">人工接管</button>':j.status==='replied'?'<button class="primary" data-action="takeover">接管并回复</button>':j.status==='followup'?'<button class="primary" data-action="send-reply">发送模拟回复</button>':j.status==='waiting'?'<button data-action="show-chat">查看沟通记录</button>':j.status==='ignored'?'<button data-action="restore">恢复考虑</button>':'<button class="primary" data-action="greet">只打招呼</button><button data-action="manage">AI托管</button>';
 return `<header class="detail-top"><div class="topline"><span class="tag neutral">${inline?'连续阅读 · 选中岗位':'岗位详情'} · 仅演示</span>${inline?'<small>点击左侧切换</small>':'<button class="icon" data-action="close" aria-label="关闭岗位详情">×</button>'}</div><h2>${j.title}</h2><p class="detail-meta">${j.company}　${j.salary}<br>${j.place} · ${j.active}</p></header><nav class="detail-tabs" aria-label="详情内容">${[['match','匹配判断'],['research','公司背调'],['jd','岗位原文'],['chat','沟通记录']].map(([k,label])=>`<button data-detail="${k}" class="${state.detailTab===k?'active':''}" aria-pressed="${state.detailTab===k}">${label}</button>`).join('')}</nav><div class="detail-body">${body}</div><footer class="detail-bottom"><div class="secondary-actions"><button data-action="save">${j.status==='saved'?'取消收藏':'收藏岗位'}</button><button data-action="ignore">暂不考虑</button></div><div class="actions">${actions}</div><small>${chat?'仅模拟状态与消息，不连接BOSS，不会真实发送。':'只打招呼：回复后由你接管。AI托管：继续处理普通对话。此处均为模拟。'}</small></footer>`;
}
function openJob(id){state.selected=Number(id);const j=jobs.find(j=>j.id===state.selected);state.detailTab=['replied','check'].includes(j.status)?'chat':'match';if(variant==='c'&&innerWidth>800){drawJobRegion();return;}$('#drawer-content').innerHTML=detail(j);$('#drawer').showModal();}
function refreshDetail(){if(state.page==='jobs')drawJobRegion({keepSelection:true});if($('#drawer').open)$('#drawer-content').innerHTML=detail(jobs.find(j=>j.id===state.selected));nav();}
function drawTasks(){const tasks=[['采集岗位',state.loginRequired?'需要你登录BOSS':state.collectionOn?'等待下次计划':'定时已暂停',state.loginRequired?'仅采集受影响；匹配、背调继续运行。':'11个关键词 · 深圳 · 每6小时',`<button data-action="mock-login">${state.loginRequired?'模拟完成登录':'查看搜索计划'}</button><button data-action="collection-toggle">${state.collectionOn?'暂停定时':'恢复定时'}</button>`],['匹配简历',state.analysisOn?'正在分析 · 3个任务':'已暂停后续分析','已生成12个值得沟通的结果',`<button data-action="analysis-toggle">${state.analysisOn?'暂停后续':'继续分析'}</button><button data-view="recommended" data-goto-jobs>看推荐</button>`],['公司背调',state.researchOn?'运行中 · 1家公司':'已暂停后续背调','同公司复用报告 · 已有3份 · 2份待核实',`<button data-action="research-toggle">${state.researchOn?'暂停背调':'开启背调'}</button><button data-action="sample-research">看报告示例</button>`],['AI沟通','1个岗位托管中','仅处理逐岗位授权的会话；新回复优先提醒',`<button data-view="communicating" data-goto-jobs>查看会话</button>`]];
 $('#page').innerHTML=`${state.loginRequired?'<div class="notice"><b>有1件事需要处理：BOSS登录已过期</b><br>完成登录即可继续采集，不用重跑已有岗位。下面的按钮只模拟恢复。</div>':''}<div class="task-list">${tasks.map(([title,status,desc,buttons])=>`<section class="task-line"><div><h3>${title}</h3><p>独立控制，不影响其他任务</p></div><div class="task-state">${status}<small>${desc}</small></div><div class="tools">${buttons}</div></section>`).join('')}</div><div class="simple-sheet" style="margin-top:20px"><details id="plan"><summary>搜索计划与关键词</summary><div class="two-col"><label>目标城市<select><option>深圳</option><option>广州</option></select></label><label>采集频率<select><option>每6小时</option><option>每天一次</option></select></label></div><p>产品经理、SaaS产品经理、B端产品经理等11个词（演示）</p><button data-action="save-plan">保存演示计划</button></details><details><summary>高级维护与诊断</summary><p>缺失字段补采、失败重试和技术日志在这里，日常无需操作。</p><button data-action="diagnostic">查看模拟诊断</button></details></div>`;}
function drawProfile(){ $('#page').innerHTML=`<div class="simple-sheet"><div class="resume-initial">当前匹配依据</div><div class="resume-header"><div><h2>示例候选人 · 产品经理</h2><p class="muted">演示简历 v${state.profileVersion} · 不含真实个人资料</p></div><button data-action="update-resume">更新简历</button></div><div class="resume-status"><span class="tag">解析完成</span><span class="tag neutral">用于岗位匹配</span></div><p>有企业服务产品、跨团队交付与业务验证经验。本页展示如何组织简历信息，不评估真实候选人。</p><details><summary>查看简历全文与原文依据</summary><h3>示例项目</h3><p>负责业务流程梳理、产品方案和交付协同。所有内容为原型占位，不作为实际匹配依据。</p></details><details id="resume-update"><summary>更新与版本记录</summary><p>正式产品会先解析并确认新版本，再说明对现有匹配结果的影响，不静默重算。</p><button data-action="use-example">使用示例新版（仅演示）</button></details><details><summary>适合的岗位与建议关键词</summary><p>B端产品经理、SaaS产品经理、平台产品经理。演示中不会修改真实搜索计划。</p><button data-action="keyword-review">查看建议</button></details><details><summary>简历表达建议</summary><p>先明确个人职责，再呈现业务成果；不把参与表述为主导。</p></details></div>`;}
function drawSettings(){const content=state.settingsTab==='preferences'?'<h2>求职偏好</h2><p>控制你优先看到的机会。偏好不等于硬性淘汰条件。</p><div class="two-col"><label>目标城市<select data-setting><option>深圳</option><option>广州</option></select></label><label>期望月薪<select data-setting><option>20–30K</option><option>25–35K</option></select></label></div><label>关注的岗位方向<input data-setting value="B端 / SaaS / 平台产品经理"></label>':state.settingsTab==='rules'?`<h2>AI规则与招呼风格</h2><p>用可理解的偏好作默认，高级提示词按需展开。</p><label>招呼风格<select id="style" data-setting>${['自然真诚','简洁直接','专业成果'].map(s=>`<option ${state.style===s?'selected':''}>${s}</option>`).join('')}</select></label><div class="verdict"><strong>风格预览（示例）</strong><p id="style-preview">${styleText()}</p></div><details><summary>自定义匹配规则 / Skill</summary><label>匹配规则<textarea data-setting>以实际职责和原文证据判断，不扩大主导范围，不因未知活跃状态直接排除。</textarea></label></details><div class="warning">修改风格仅影响招呼；修改匹配规则会影响匹配结果。正式保存前应显示受影响范围。</div>`:state.settingsTab==='model'?'<h2>模型与额度</h2><p>正常情况下不需要调整。任务预算不是金额，也不等于模型请求数。</p><label>并发任务数<input type="number" value="4" min="1" max="16" data-setting></label><label>每日任务预算<input type="number" value="200" min="1" data-setting></label><p>公司背调可能包含多轮模型调用。实际费用以服务商为准。</p>':'<h2>高级设置</h2><p>版本、数据导出和运行诊断集中在这里。</p><details><summary>本地运行与隐私</summary><p>原型完全使用内存数据，刷新或重置后恢复初始状态。没有任何生产API调用。</p></details><button data-action="diagnostic">查看演示状态</button>';
 $('#page').innerHTML=`<div class="pill-buttons">${[['preferences','求职偏好'],['rules','AI规则'],['model','模型与额度'],['advanced','高级']].map(([k,v])=>`<button data-settings="${k}" class="${state.settingsTab===k?'active':''}">${v}</button>`).join('')}</div><div class="simple-sheet">${content}<div class="save-bar"><span id="save-state">${state.dirty?'有未保存的更改':'演示设置已载入'}</span><button class="primary" data-action="save-settings">保存演示设置</button></div><p id="dirty-warning" class="warning" hidden>你有未保存的演示更改。请先保存或<button class="quiet" data-action="discard">放弃更改</button>，再切换页面。</p></div>`;document.querySelectorAll('[data-setting]').forEach((field,i)=>{const key=state.settingsTab+':'+i;field.dataset.cacheKey=key;if(settingValues.has(key))field.value=settingValues.get(key);});}
function styleText(){return state.style==='简洁直接'?'您好，关注这个产品经理岗位。我有企业服务产品与交付相关经验，希望了解团队当前的重点。':state.style==='专业成果'?'您好，我有复杂业务流程设计和跨团队交付实践，希望结合岗位具体目标介绍相关项目。':'您好，看到这个岗位的业务方向与我的产品经历比较接近，想进一步了解团队正在解决的问题。';}
function navigate(page){if(state.dirty){$('#dirty-warning').hidden=false;notify('请先保存或放弃未保存的演示更改');return;}state.page=page;state.detailTab='match';draw();window.scrollTo(0,0);}
document.addEventListener('input',e=>{if(e.target.id==='search'){state.query=e.target.value;drawJobRegion();}if(e.target.matches('[data-setting]')){settingValues.set(e.target.dataset.cacheKey,e.target.value);state.dirty=true;$('#save-state').textContent='有未保存的更改';}});
document.addEventListener('change',e=>{if(e.target.matches('[data-setting]')){settingValues.set(e.target.dataset.cacheKey,e.target.value);state.dirty=true;$('#save-state').textContent='有未保存的更改';if(e.target.id==='style'){state.style=e.target.value;$('#style-preview').textContent=styleText();}}});
document.addEventListener('click',e=>{
 const btn=e.target.closest('button');if(!btn)return;
 if(btn.dataset.page){navigate(btn.dataset.page);return;}
 if(btn.dataset.view){if(state.dirty){notify('请先保存设置');return;}state.page='jobs';state.view=btn.dataset.view;state.selected=null;draw();return;}
 if(btn.dataset.open){openJob(btn.dataset.open);return;}
 if(btn.dataset.detail){state.detailTab=btn.dataset.detail;refreshDetail();return;}
 if(btn.dataset.settings){if(state.dirty){$('#dirty-warning').hidden=false;return;}state.settingsTab=btn.dataset.settings;drawSettings();return;}
 if(btn.dataset.clear){state[btn.dataset.clear]='';drawJobs();return;}
 const act=btn.dataset.action;if(!act)return;
 const j=jobs.find(j=>j.id===state.selected);
 if(act==='filter'){$('#salary').value=state.salary;$('#activity').value=state.activity;$('#filters').showModal();return;}
 if(act==='reset-filter'){state.query='';state.salary='';state.activity='';state.view='all';drawJobs();return;}
 if(act==='close'){$('#drawer').close();return;}
 if(act==='collection-toggle'){state.collectionOn=!state.collectionOn;drawTasks();notify(state.collectionOn?'已模拟恢复定时采集':'已模拟暂停后续定时，不影响其他任务');return;}
 if(act==='analysis-toggle'){state.analysisOn=!state.analysisOn;drawTasks();return;}
 if(act==='research-toggle'){state.researchOn=!state.researchOn;drawTasks();notify('只改变本原型的背调状态');return;}
 if(act==='mock-login'){if(state.loginRequired){state.loginRequired=false;drawTasks();notify('已模拟恢复登录，原型没有访问BOSS');}else $('#plan').open=true;return;}
 if(act==='save-plan'){notify('搜索计划已模拟保存，不影响真实任务');return;}
 if(act==='diagnostic'){notify('模拟诊断：未连接生产服务，真实发送次数为0');return;}
 if(act==='sample-research'){state.page='jobs';state.view='all';draw();openJob(1);state.detailTab='research';refreshDetail();return;}
 if(act==='update-resume'){$('#resume-update').open=true;return;}
 if(act==='use-example'){state.profileVersion++;drawProfile();notify('已换用示例版本，没有改动你的简历');return;}
 if(act==='keyword-review'){notify('关键词仅供预览，本原型不会加入真实搜索');return;}
 if(act==='save-settings'){state.dirty=false;savedSettingValues=new Map(settingValues);savedStyle=state.style;$('#save-state').textContent='已保存到本次演示';$('#dirty-warning').hidden=true;notify('演示设置已保存，不影响实际配置');return;}
 if(act==='discard'){state.dirty=false;state.style=savedStyle;settingValues=new Map(savedSettingValues);drawSettings();return;}
 if(!j)return;
 if(act==='greet'){j.status='waiting';state.detailTab='chat';notify('已模拟发送招呼，等待HR回复；真实发送0条');}
 if(act==='manage'){j.status='managed';state.detailTab='chat';notify('已模拟开启此岗位AI托管，不影响其他岗位');}
 if(act==='takeover'){j.status='followup';state.detailTab='chat';notify('已模拟人工接管，AI不再继续回复');}
 if(act==='mock-reply'){j.message='谢谢介绍，能具体说说您在这个项目中的职责，以及遇到的主要难点吗？';j.status='replied';notify('收到一条示例回复，已放入待我处理');}
 if(act==='reconcile'){j.status='waiting';state.detailTab='chat';notify('已模拟核对：原消息已发送，没有重发');}
 if(act==='send-reply'){if(state.detailTab!=='chat'){state.detailTab='chat';refreshDetail();return;}const value=$('#drawer').open?$('#drawer #reply')?.value:$('.reading-pane #reply')?.value;if(!value?.trim()){notify('请先输入示例回复');return;}j.reply=value.trim();j.status='waiting';notify('已保存模拟回复，真实发送0条');}
 if(act==='save-note'){j.note=($('#drawer').open?$('#drawer #note'):$('.reading-pane #note'))?.value||'';notify('演示备注已保存');}
 if(act==='show-chat')state.detailTab='chat';
 if(act==='save'){if(['new','saved'].includes(j.status))j.status=j.status==='saved'?'new':'saved';notify('收藏状态已更新（演示）');}
 if(act==='ignore'){if(j.status==='managed'){notify('请先人工接管，再将岗位暂不考虑');return;}if(j.status!=='ignored')j.previousStatus=j.status;j.status='ignored';notify('已暂不考虑；可在全部岗位恢复');}
 if(act==='restore'){j.status=j.previousStatus||'new';notify('已恢复考虑，原沟通进度保留');}
 refreshDetail();
});
$('#apply-filters').onclick=()=>{state.salary=$('#salary').value;state.activity=$('#activity').value;$('#filters').close();drawJobs();};
$('#clear-filters').onclick=()=>{$('#salary').value='';$('#activity').value='';};
$('#reset').onclick=()=>location.reload();
$('#drawer').addEventListener('close',()=>{if(state.page==='jobs'){const id=state.selected;drawJobs();document.querySelector(`[data-open="${id}"]`)?.focus({preventScroll:true});}});
window.addEventListener('resize',()=>{if(state.page==='jobs'&&variant==='c'&&!$('#drawer').open)drawJobRegion();});
draw();
